import React from 'react'
export const eventArray = [
  {label: "10 Сильный ветер", value: 10, isDangerous: false},
  {label: <b>11 Очень сильный ветер</b>, value: 11, isDangerous: true},
  {label: <b>12 Ураганный ветер</b>, value: 12, isDangerous: true},
  {label: "16 Шквал, НГЯ", value: 16, isDangerous: false},
  {label: <b>17 Шквал, ОЯ</b>, value: 17, isDangerous: true},
  {label: <b>18 Смерч над водной поверхностью</b>, value: 18, isDangerous: true},
  {label: <b>19 Смерч над сушей</b>, value: 19, isDangerous: true},
  {label: <b>21 Сильная жара</b>, value: 21, isDangerous: true},
  {label: <b>22 Аномально-жаркая погода</b>, value: 22, isDangerous: true},
  {label: <b>24 Чрезвычайная пожарная опасность</b>, value: 24, isDangerous: true},
  {label: <b>25 Сильный мороз</b>, value: 25, isDangerous: true},
  {label: <b>26 Аномально-холодная погода</b>, value: 26, isDangerous: true},
  {label: "30 Низкая облачность при 5 баллах и более", value: 30, isDangerous: false},
  {label: "31 Закрытие гор, перевалов облаками, осадками, туманом", value: 31, isDangerous: false},
  {label: "35 Пыльная (песчаная) буря", value: 35, isDangerous: false},
  {label: <b>36 Сильная пыльная (песчаная) буря</b>, value: 36, isDangerous: true},
  {label: "37 Метель низовая", value: 37, isDangerous: false},
  {label: "38 Метель общая", value: 38, isDangerous: false},
  {label: <b>39 Сильная метель</b>, value: 39, isDangerous: true},
  {label: "40 Ухудшение видимости при осадках", value: 40, isDangerous: false},
  {label: "41 Ухудшение видимости из-за дыма", value: 41, isDangerous: false},
  {label: "42 Ухудшение видимости из-за мглы", value: 42, isDangerous: false},
  {label: "43 Ухудшение видимости из-за дымки", value: 43, isDangerous: false},
  {label: "44 Ухудшение видимости из-за тумана", value: 44, isDangerous: false},
  {label: <b>47 Сильный туман</b>, value: 47, isDangerous: true},
  {label: "51 Гололедица на дорогах", value: 51, isDangerous: false},
  {label: "52 Изморозь", value: 52, isDangerous: false},
  {label: <b>53 Сильная изморозь</b>, value: 53, isDangerous: true},
  {label: "54 Гололед", value: 54, isDangerous: false},
  {label: <b>55 Сильный гололед</b>, value: 55, isDangerous: true},
  {label: "56 Отложение мокрого снега", value: 56, isDangerous: false},
  {label: <b>57 Сильное отложение мокрого снега</b>, value: 57, isDangerous: true},
  {label: "58 Сложное отложение", value: 58, isDangerous: false},
  {label: <b>59 Сильное сложное отложение</b>, value: 59, isDangerous: true},
  {label: <b>62 Продолжительный сильный дождь</b>, value: 62, isDangerous: true},
  {label: "63 Сильный дождь (дождь, ливневый дождь)", value: 63, isDangerous: false},
  {label: <b>64 Очень сильный дождь (дождь, ливневый дождь)</b>, value: 64, isDangerous: true},
  {label: "65 Сильные смешанные осадки (мокрый снег, дождь со снегом)", value: 65, isDangerous: false},
  {label: <b>66 Очень сильные смешанные осадки (мокрый снег, дождь со снегом)</b>, value: 66, isDangerous: true},
  {label: "68 Ледяной дождь", value: 68, isDangerous: false},
  {label: "81 Ливень", value: 81, isDangerous: false},
  {label: <b>82 Сильный ливень</b>, value: 82, isDangerous: true},
  {label: "85 Сильнй снег (снег, ливневый снег и др.)", value: 85, isDangerous: false},
  {label: <b>86 Очень сильный снег (снег, ливневый снег и др.)</b>, value: 86, isDangerous: true},
  {label: "89 Град", value: 89, isDangerous: false},
  {label: <b>90 Крупный град</b>, value: 90, isDangerous: true},
  {label: "91 Гроза на станции", value: 91, isDangerous: false},
  {label: "92 Гроза в окрестности", value: 92, isDangerous: false},
]