default: &default
  adapter: mysql2
  encoding: utf8
  username: slavam1
  # password:
  password: slavam1
  host: localhost
  port: 3306

meteo:  
  adapter: mysql2
  encoding: utf8
  username: meteo
  password: meteo2015
  host: 10.105.24.9
  port: 3306
  database: meteo
  
chemist: 
  <<: *default
  database: akiam
  # database: chemical # Gorlovka

meteo2017:
  <<: *default
  database: meteo2017
  
development:
  <<: *default
  database: hmc_development
  # database: meteo2017
  # database: c9
  # database: meteo_dev

test:
  <<: *default
  database: hmc_test

production:
  <<: *default
  database: hmc_production
  username: db-admin
  
